import type { Component } from 'vue'
import {
  ArrowUpRight,
  Camera,
  CloudUpload,
  FolderOpen,
  Headphones,
  Heart,
  Monitor,
  Repeat,
  Repeat1,
  Shuffle,
  Smartphone,
  Volume1,
  VolumeX,
  ArrowRight,
  AudioLines,
  Beer,
  BookOpen,
  Bookmark,
  CalendarDays,
  Check,
  Ellipsis,
  ListMusic,
  ListPlus,
  Minus,
  ChefHat,
  Compass,
  Dices,
  ImagePlus,
  MapPin,
  PenLine,
  RefreshCw,
  Star,
  Trash2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CodeXml,
  Command,
  Flag,
  GlassWater,
  House,
  Images,
  LogOut,
  Martini,
  Music,
  Pause,
  Play,
  Plus,
  Search,
  Settings,
  Shield,
  SkipBack,
  SkipForward,
  Sparkles,
  Trophy,
  User,
  UtensilsCrossed,
  Volume2,
  Wine,
  X,
} from 'lucide-vue-next'

/**
 * Named icon registry so icons can be referenced from plain data (route meta,
 * command palette entries, API payloads). Mobile can mirror the same names.
 */
export const icons = {
  home: House,
  listening: AudioLines,
  music: Music,
  code: CodeXml,
  cellar: Wine,
  wine: Wine,
  beer: Beer,
  spirits: Martini,
  kitchen: ChefHat,
  'food-drink': UtensilsCrossed,
  library: BookOpen,
  f1: Flag,
  sports: Trophy,
  media: Images,
  admin: Shield,
  profile: User,
  search: Search,
  command: Command,
  plus: Plus,
  clock: Clock,
  sparkles: Sparkles,
  settings: Settings,
  'log-out': LogOut,
  'arrow-right': ArrowRight,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  check: Check,
  close: X,
  play: Play,
  pause: Pause,
  next: SkipForward,
  previous: SkipBack,
  volume: Volume2,
  'volume-low': Volume1,
  'volume-off': VolumeX,
  glass: GlassWater,
  heart: Heart,
  shuffle: Shuffle,
  repeat: Repeat,
  'repeat-one': Repeat1,
  monitor: Monitor,
  smartphone: Smartphone,
  'external-link': ArrowUpRight,
  headphones: Headphones,
  star: Star,
  image: ImagePlus,
  upload: CloudUpload,
  camera: Camera,
  folder: FolderOpen,
  trash: Trash2,
  edit: PenLine,
  refresh: RefreshCw,
  bookmark: Bookmark,
  compass: Compass,
  dice: Dices,
  pin: MapPin,
  calendar: CalendarDays,
  queue: ListMusic,
  'list-plus': ListPlus,
  more: Ellipsis,
  minus: Minus,
} satisfies Record<string, Component>

export type IconName = keyof typeof icons
