/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/sidebar/AppSidebar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    NexusAvatar: typeof import('./components/nexus-avatar/NexusAvatar.vue')['default']
    NexusGithubChrome: typeof import('./components/nexus-github-chrome/NexusGithubChrome.vue')['default']
    NexusGithubIcon: typeof import('./components/nexus-github-icon/NexusGithubIcon.vue')['default']
    NexusPageWrapper: typeof import('./components/nexus-page-wrapper/NexusPageWrapper.vue')['default']
    NexusSidebar: typeof import('./components/nexus-sidebar/NexusSidebar.vue')['default']
    NexusSpotifyAddToPlaylist: typeof import('./components/nexus-spotify-add-to-playlist/NexusSpotifyAddToPlaylist.vue')['default']
    NexusSpotifyChrome: typeof import('./components/nexus-spotify-chrome/NexusSpotifyChrome.vue')['default']
    NexusSpotifyIcon: typeof import('./components/nexus-spotify-icon/NexusSpotifyIcon.vue')['default']
    NexusSpotifyOnRepeat: typeof import('./components/nexus-spotify-on-repeat/NexusSpotifyOnRepeat.vue')['default']
    NexusSpotifyPlayer: typeof import('./components/nexus-spotify-player/NexusSpotifyPlayer.vue')['default']
    NexusSpotifyQueuePanel: typeof import('./components/nexus-spotify-queue-panel/NexusSpotifyQueuePanel.vue')['default']
    NexusSpotifyResumeCard: typeof import('./components/nexus-spotify-resume-card/NexusSpotifyResumeCard.vue')['default']
    NexusSpotifyTrackRow: typeof import('./components/nexus-spotify-track-row/NexusSpotifyTrackRow.vue')['default']
    PageWrapper: typeof import('./components/page-wrapper/PageWrapper.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Slider: typeof import('primevue/slider')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
