/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    NexusAvatar: typeof import('./components/nexus-avatar/NexusAvatar.vue')['default']
    NexusChart: typeof import('./components/nexus-chart/NexusChart.vue')['default']
    NexusDataTable: typeof import('./components/nexus-data-table/NexusDataTable.vue')['default']
    NexusDrinkAnalysisPanel: typeof import('./components/nexus-drink-analysis-panel/NexusDrinkAnalysisPanel.vue')['default']
    NexusF1LockoutBanner: typeof import('./components/nexus-f1-lockout-banner/NexusF1LockoutBanner.vue')['default']
    NexusF1TrackReplay: typeof import('./components/nexus-f1-track-replay/NexusF1TrackReplay.vue')['default']
    NexusGithubDiffViewer: typeof import('./components/nexus-github-diff-viewer/NexusGithubDiffViewer.vue')['default']
    NexusGithubIcon: typeof import('./components/nexus-github-icon/NexusGithubIcon.vue')['default']
    NexusImage: typeof import('./components/nexus-image/NexusImage.vue')['default']
    NexusImageUploader: typeof import('./components/nexus-image-uploader/NexusImageUploader.vue')['default']
    NexusImageViewer: typeof import('./components/nexus-image-viewer/NexusImageViewer.vue')['default']
    NexusPairingPicker: typeof import('./components/nexus-pairing-picker/NexusPairingPicker.vue')['default']
    NexusQuotaBadge: typeof import('./components/nexus-quota-badge/NexusQuotaBadge.vue')['default']
    NexusRatingInput: typeof import('./components/nexus-rating-input/NexusRatingInput.vue')['default']
    NexusRecipeDetail: typeof import('./components/nexus-recipe-detail/NexusRecipeDetail.vue')['default']
    NexusSportIcon: typeof import('./components/nexus-sport-icon/NexusSportIcon.vue')['default']
    NexusSpotifyAddToPlaylist: typeof import('./components/nexus-spotify-add-to-playlist/NexusSpotifyAddToPlaylist.vue')['default']
    NexusSpotifyIcon: typeof import('./components/nexus-spotify-icon/NexusSpotifyIcon.vue')['default']
    NexusSpotifyNowPlaying: typeof import('./components/nexus-spotify-now-playing/NexusSpotifyNowPlaying.vue')['default']
    NexusSpotifyPlayerPanel: typeof import('./components/nexus-spotify-player-panel/NexusSpotifyPlayerPanel.vue')['default']
    NexusSpotifyPlayingIndicator: typeof import('./components/nexus-spotify-playing-indicator/NexusSpotifyPlayingIndicator.vue')['default']
    NexusSpotifyQueuePanel: typeof import('./components/nexus-spotify-queue-panel/NexusSpotifyQueuePanel.vue')['default']
    NexusSpotifySimilarRecs: typeof import('./components/nexus-spotify-similar-recs/NexusSpotifySimilarRecs.vue')['default']
    NexusSpotifyTrackMetrics: typeof import('./components/nexus-spotify-track-metrics/NexusSpotifyTrackMetrics.vue')['default']
    NexusSpotifyTrackRow: typeof import('./components/nexus-spotify-track-row/NexusSpotifyTrackRow.vue')['default']
    NexusTableChip: typeof import('./components/nexus-data-table/NexusTableChip.vue')['default']
    NexusTastingTimeline: typeof import('./components/nexus-tasting-timeline/NexusTastingTimeline.vue')['default']
    NexusTeamBadge: typeof import('./components/nexus-team-badge/NexusTeamBadge.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
